# Generated by Django 5.2.10 on 2026-02-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_add_thumbnail_to_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
